#!/bin/bash

DIR="$1"
if [ -f "$DIR" ]; then
    DIR=$(dirname "$DIR")
fi

if [ ! -d "$DIR" ] | [ ! -r "$DIR/start.novel" ] | [ ! -r "$DIR/main.ray" ]; then
    DEFAULT_PATH="";
    if [ -z "$DIR" ]; then
	DEFAULT_PATH="";
    else
	DEFAULT_PATH="$DIR/";
    fi

    export GTK_USE_PORTAL=1;
    DIR=$(zenity --title "Suika3 Engine" \
                 --file-selection \
                 --directory \
                 --filename="$DEFAULT_PATH");

    if [ -z "$DIR" ]; then
        exit 1;
    fi;
fi

if cd "$DIR"; then
    rm -f log.txt;
    suika3;
    if [ -f log.txt ]; then
        zenity --error \
               --title="Suika3 Engine" \
               --text="$(printf 'Error\n%s' "$(cat log.txt)")";
        exit 1;
    fi;
else
    zenity --error \
           --title="Suika3 Engine" \
           --text="Failed to access the directory:\n$WD\n\nPlease check your Flatpak permission settings."
    exit 1
fi
