[DEFAULT]
debian-branch = main
upstream-branch = main
upstream-tag = %(version)s
debian-tag = debian/%(version)s

[buildpackage]
pristine-tar = True
git-ignore-new = False

[dch]
ignore-branch = False
git-log = --no-merges
git-author = True

[import-orig]
pristine-tar = True
