/* -*- coding: utf-8; tab-width: 8; indent-tabs-mode: t; -*- */

/*
 * Noct Programming Language
 * Copyright (c) 2025, 2026, Awe Morris
 */

/*
 * Host harness for the C translation backend test.
 *
 * Linked together with a C source generated by "noct --ansic", it
 * registers the translated functions via init_aot_code() and runs
 * main().  A minimal print() is provided with the same scalar
 * formatting as the CLI so that golden outputs generated by the
 * interpreter can be compared directly.
 */

#include <noct/noct.h>
#include <inttypes.h>
#include <stdio.h>

/* Implementation of print() (scalar values only). */
static bool
cfunc_print(
	NoctEnv *env)
{
	NoctValue value;
	int type;
	int ival;
	int64_t lval;
	float fval;
	double lfval;
	const char *sval;
	bool ok;

	if (!noct_pin_local(env, 1, &value))
		return false;

	ok = false;
	do {
		if (!noct_get_arg(env, 0, &value))
			break;
		if (!noct_get_value_type(env, &value, &type))
			break;
		switch (type) {
		case NOCT_VALUE_INT:
			if (!noct_get_int(env, &value, &ival))
				break;
			printf("%d\n", ival);
			ok = true;
			break;
		case NOCT_VALUE_LONG:
			if (!noct_get_long(env, &value, &lval))
				break;
			printf("%" PRId64 "\n", lval);
			ok = true;
			break;
		case NOCT_VALUE_FLOAT:
			if (!noct_get_float(env, &value, &fval))
				break;
			printf("%.7g\n", fval);
			ok = true;
			break;
		case NOCT_VALUE_DOUBLE:
			if (!noct_get_double(env, &value, &lfval))
				break;
			printf("%.15g\n", lfval);
			ok = true;
			break;
		case NOCT_VALUE_STRING:
			if (!noct_get_string(env, &value, &sval))
				break;
			printf("%s\n", sval);
			ok = true;
			break;
		default:
			noct_error(env, "print: unsupported type.");
			break;
		}
	} while (0);

	noct_unpin_local(env, 1, &value);

	return ok;
}

int
main(void)
{
	NoctVM *vm;
	NoctEnv *env;
	NoctConfig config;
	NoctValue ret;
	const char *param[] = {"msg"};
	const char *msg;

	noct_set_default_config(&config);
	if (!noct_create_vm(&vm, &env, &config)) {
		printf("Failed to create VM.\n");
		return 1;
	}

	if (!noct_register_cfunc(env, "print", 1, param, cfunc_print, NULL)) {
		printf("Failed to register print().\n");
		return 1;
	}

	if (!init_aot_code(env)) {
		printf("Failed to register AOT functions.\n");
		return 1;
	}

	if (!noct_enter_vm(env, "main", 0, NULL, &ret)) {
		if (noct_get_error_message(env, &msg))
			printf("Error: %s\n", msg);
		return 1;
	}

	if (!noct_destroy_vm(vm))
		return 1;

	return 0;
}
