set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(CMAKE_C_COMPILER wcl386)
set(CMAKE_CXX_COMPILER wcl386)

set(CMAKE_C_COMPILER_TARGET windows)
set(CMAKE_CXX_COMPILER_TARGET windows)

set(CMAKE_C_FLAGS_INIT "-bt=windows -oneatx -oe=200 -oh -oi -zp4 -fpi87")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_STATIC_LIBRARY_SUFFIX ".lib" CACHE STRING "" FORCE)
